MODEL := os-model.py
MOSAIC := mosaic.py

run-hello:
	python3.11 $(MODEL) hello.py

run-threads:
	python3.11 $(MODEL) threads.py

m-hello:
	python3.11 $(MOSAIC) m_hello.py

m-mix:
	python3.11 $(MOSAIC) m_mix.py